# Generated by Django 3.1.6 on 2021-04-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0002_auto_20210420_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deliv_address_street',
            field=models.CharField(default='Bienweg', max_length=256),
        ),
    ]
