# Generated by Django 3.1.6 on 2021-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0003_user_deliv_address_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deliv_address_city',
            field=models.CharField(default='Nürnberg', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='deliv_address_houseno',
            field=models.CharField(default='32', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='deliv_address_zipcode',
            field=models.CharField(default='90425', max_length=5),
        ),
    ]
