# Generated by Django 3.1.6 on 2021-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0004_auto_20210420_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deliv_address_country',
            field=models.CharField(default='Germany', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='deliv_address_city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='deliv_address_houseno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='deliv_address_street',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='deliv_address_zipcode',
            field=models.CharField(max_length=5),
        ),
    ]
