# Generated by Django 3.1.6 on 2021-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=False),
        ),
    ]
