# Generated by Django 3.1.6 on 2021-04-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0007_category_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_large', models.ImageField(upload_to='')),
            ],
        ),
    ]
