# Generated by Django 3.1.6 on 2021-04-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0008_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_large',
            field=models.ImageField(upload_to='images'),
        ),
    ]
