# Generated by Django 3.1.6 on 2021-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0010_article_contentunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentunit',
            name='description',
            field=models.CharField(default='', max_length=20),
        ),
    ]
