# Generated by Django 3.1.6 on 2021-04-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinx', '0013_article_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_qty',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
